# Generated by Django 5.1.7 on 2025-05-06 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CateringBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catering_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('description', models.TextField(blank=True)),
                ('about_us', models.TextField(blank=True)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('successful_events', models.PositiveIntegerField(default=0)),
                ('business_email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('working_days', models.CharField(blank=True, max_length=100)),
                ('slogan', models.CharField(blank=True, max_length=255)),
                ('why_choose_us', models.TextField(blank=True)),
                ('facebook_link', models.URLField(blank=True)),
                ('instagram_link', models.URLField(blank=True)),
                ('twitter_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CateringCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='posts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(default='customer', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_groups', to='myapp.register')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('category', models.CharField(max_length=50)),
                ('mealType', models.JSONField()),
                ('cuisine', models.CharField(blank=True, max_length=50, null=True)),
                ('foodType', models.CharField(max_length=50)),
                ('dietary', models.JSONField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='myapp.register')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=100)),
                ('eventtype', models.CharField(max_length=50)),
                ('eventdate', models.DateField()),
                ('eventtime', models.TimeField()),
                ('venue', models.CharField(max_length=200)),
                ('numberofguests', models.PositiveIntegerField()),
                ('hostname', models.CharField(max_length=100)),
                ('contactnumber', models.CharField(max_length=15)),
                ('permission', models.CharField(default='Pending', max_length=100)),
                ('catering_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='myapp.cateringbusiness')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='myapp.register')),
            ],
        ),
        migrations.AddField(
            model_name='cateringbusiness',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'caterer'}, on_delete=django.db.models.deletion.CASCADE, related_name='business', to='myapp.register'),
        ),
    ]
