# Generated by Django 5.1.7 on 2025-05-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_register_role_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='week',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
