# Generated by Django 5.1.7 on 2025-05-06 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_course_week'),
    ]

    operations = [
        migrations.DeleteModel(
            name='about',
        ),
        migrations.RemoveField(
            model_name='cateringbusiness',
            name='user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='catering_business',
        ),
        migrations.DeleteModel(
            name='CateringCards',
        ),
        migrations.DeleteModel(
            name='Contact_Details',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='menuitemgroup',
            name='user',
        ),
        migrations.DeleteModel(
            name='CateringBusiness',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.DeleteModel(
            name='MenuItemGroup',
        ),
    ]
