# Generated by Django 5.1.7 on 2025-05-06 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='course',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='course',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='course',
            name='week',
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('data_science', 'Data Science'), ('programming', 'Programming'), ('web_development', 'Web Development'), ('ai_ml', 'AI & Machine Learning'), ('cloud_computing', 'Cloud Computing')], default='programming', help_text='Select the category that best fits this course.', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(help_text='Provide a detailed description of the course content.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', help_text='Select the course difficulty level.', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Upload a course thumbnail (JPG, JPEG, PNG only).', null=True, upload_to='course_thumbnails/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(help_text='Enter a short and descriptive course title.', max_length=150),
        ),
    ]
