# Generated by Django 5.1.7 on 2025-05-06 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_course_category_alter_course_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Module',
        ),
    ]
