# Generated by Django 5.1.7 on 2025-05-07 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='myapp.register'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_enrollments', to='myapp.register'),
        ),
    ]
