# Generated by Django 5.1.7 on 2025-05-08 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_question_option_quiz_question_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('Not Completed', 'Not Completed'), ('Completed', 'Completed'), ('In Progress', 'In Progress')], default='Not Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='myapp.register'),
        ),
    ]
