# Generated by Django 5.1.7 on 2025-05-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_enrollment_status_alter_enrollment_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='module_status',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='quiz_status',
            field=models.JSONField(default=list),
        ),
    ]
