# Generated by Django 5.1.7 on 2025-05-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_enrollment_module_status_enrollment_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='quiz_status',
            field=models.CharField(max_length=100),
        ),
    ]
