# Generated by Django 5.1.7 on 2025-05-08 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_enrollment_quiz_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='quiz_status',
        ),
    ]
