# Generated by Django 5.1.7 on 2025-05-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_enrollment_quiz_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='quiz_status',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
