# Generated by Django 5.1.7 on 2025-05-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_enrollment_quiz_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='quiz_status',
            field=models.IntegerField(default=0),
        ),
    ]
